package com.riga.voicewaze.domain.landmark

object LandmarkDefaults {
    val entries: List<LandmarkEntry> = listOf(
        LandmarkEntry(id = 1L, spokenPhrase = "аэропорт", displayName = "аэропорт", address = "Starptautiskā lidosta Rīga, Mārupes novads, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 2L, spokenPhrase = "вокзал", displayName = "вокзал", address = "Stacijas laukums 2, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 3L, spokenPhrase = "автовокзал", displayName = "автовокзал", address = "Prāgas iela 1, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 4L, spokenPhrase = "рынок", displayName = "рынок", address = "Nēģu iela 7, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 5L, spokenPhrase = "цирк", displayName = "цирк", address = "Merķeļa iela 4, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 6L, spokenPhrase = "мильда", displayName = "мильда", address = "Brīvības laukums 1, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 7L, spokenPhrase = "латвия", displayName = "латвия", address = "Elizabetes iela 55, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 8L, spokenPhrase = "даугава", displayName = "даугава", address = "Kuģu iela 24, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 9L, spokenPhrase = "ридзене", displayName = "ридзене", address = "Reimersa iela 1, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 10L, spokenPhrase = "элизабетта", displayName = "элизабетта", address = "Elizabetes iela 73, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 11L, spokenPhrase = "талинк", displayName = "талинк", address = "Elizabetes iela 24, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 12L, spokenPhrase = "олд таун", displayName = "олд таун", address = "Zigfrīda Annas Meierovica bulvāris 10, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 13L, spokenPhrase = "астор", displayName = "астор", address = "Zigfrīda Annas Meierovica bulvāris 10, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 14L, spokenPhrase = "гранд палас", displayName = "гранд палас", address = "Pils iela 12, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 15L, spokenPhrase = "нейбург", displayName = "нейбург", address = "Jauniela 25/27, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 16L, spokenPhrase = "риверсайт", displayName = "риверсайт", address = "11. novembra krastmala 33, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 17L, spokenPhrase = "велтон олд рига", displayName = "велтон олд рига", address = "Vaļņu iela 49, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 18L, spokenPhrase = "центрум", displayName = "центрум", address = "Kalēju iela 33, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 19L, spokenPhrase = "велтон рига", displayName = "велтон рига", address = "Vaļņu iela 49, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 20L, spokenPhrase = "метрополь", displayName = "метрополь", address = "Aspazijas bulvāris 36/38, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 21L, spokenPhrase = "форум", displayName = "форум", address = "Vaļņu iela 45, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 22L, spokenPhrase = "риксвелл централ", displayName = "риксвелл централ", address = "Elizabetes iela 101, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 23L, spokenPhrase = "риксвелл олд рига", displayName = "риксвелл олд рига", address = "Minsterejas iela 8/10, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 24L, spokenPhrase = "гутэнбэрк", displayName = "гутэнбэрк", address = "Doma laukums 1, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 25L, spokenPhrase = "юрмала спа", displayName = "юрмала спа", address = "Jomas iela 47/49, Jūrmala, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 26L, spokenPhrase = "балтик бич", displayName = "балтик бич", address = "Jūras iela 23/25, Jūrmala, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 27L, spokenPhrase = "самарах", displayName = "самарах", address = "Bulduru prospekts 64/68, Jūrmala, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 28L, spokenPhrase = "эйси мариет", displayName = "эйси мариет", address = "Dzirnavu iela 33, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 29L, spokenPhrase = "амэла", displayName = "амэла", address = "Ausekļa iela 22, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 30L, spokenPhrase = "астон", displayName = "астон", address = "Zigfrīda Annas Meierovica bulvāris 10, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 31L, spokenPhrase = "авалон", displayName = "авалон", address = "13. janvāra iela 19, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 32L, spokenPhrase = "бэлэвью", displayName = "бэлэвью", address = "Slokas iela 1, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 33L, spokenPhrase = "бэргс", displayName = "бэргс", address = "Elizabetes iela 83/85, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 34L, spokenPhrase = "додо", displayName = "додо", address = "Jersikas iela 1, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 35L, spokenPhrase = "домэ хостэл", displayName = "домэ хостэл", address = "8 Maza Jaunavaru iela, Riga", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 36L, spokenPhrase = "дома хостэл", displayName = "дома хостэл", address = "Mārstaļu iela 1, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 37L, spokenPhrase = "домус хостэл", displayName = "домус хостэл", address = "Tirgoņu iela 9, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 38L, spokenPhrase = "гранд поэт", displayName = "гранд поэт", address = "Raiņa bulvāris 5/6, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 39L, spokenPhrase = "драуги", displayName = "драуги", address = "Mārstaļu iela 3, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 40L, spokenPhrase = "джюгент", displayName = "джюгент", address = "Pulkveža Brieža iela 11, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 41L, spokenPhrase = "юстус", displayName = "юстус", address = "Jauniela 24, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 42L, spokenPhrase = "исландэ", displayName = "исландэ", address = "Ķīpsalas iela 2, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 43L, spokenPhrase = "кемпински", displayName = "кемпински", address = "Aspazijas bulvāris 22, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 44L, spokenPhrase = "конвэнта сэта", displayName = "конвэнта сэта", address = "Kalēju iela 9/11, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 45L, spokenPhrase = "мара", displayName = "мара", address = "Kalnciema iela 186, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 46L, spokenPhrase = "мэркурс", displayName = "мэркурс", address = "Elizabetes iela 101, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 47L, spokenPhrase = "моника", displayName = "моника", address = "Elizabetes iela 21, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 48L, spokenPhrase = "монте-кристо", displayName = "монте-кристо", address = "Kalēju iela 56, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 49L, spokenPhrase = "окей", displayName = "окей", address = "Slokas iela 12, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 50L, spokenPhrase = "опера", displayName = "опера", address = "Raiņa bulvāris 33, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 51L, spokenPhrase = "опера и балет", displayName = "опера и балет", address = "Aspazijas bulvāris 3, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 52L, spokenPhrase = "пулман", displayName = "пулман", address = "Jēkaba iela 24, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 53L, spokenPhrase = "томо", displayName = "томо", address = "Raunas iela 44, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 54L, spokenPhrase = "веф", displayName = "веф", address = "Brīvības gatve 199c, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 55L, spokenPhrase = "вэцрига", displayName = "вэцрига", address = "Gleznotāju iela 12/14, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 56L, spokenPhrase = "виктория", displayName = "виктория", address = "Aleksandra Čaka iela 55, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 57L, spokenPhrase = "дзинтари", displayName = "дзинтари", address = "Turaidas iela 1, Jūrmala, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 58L, spokenPhrase = "аквапарк", displayName = "аквапарк", address = "Viestura iela 24, Jūrmala, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 59L, spokenPhrase = "домой", displayName = "домой", address = "Ieriķu iela 33, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 60L, spokenPhrase = "стоянка", displayName = "стоянка", address = "Ieriķu iela 41A, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 61L, spokenPhrase = "сэрвис", displayName = "сэрвис", address = "Lubānas iela 99, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 62L, spokenPhrase = "николай", displayName = "николай", address = "Saharova iela 8, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 63L, spokenPhrase = "айвар", displayName = "айвар", address = "Pavasara iela 35, Baloži, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 64L, spokenPhrase = "лачупес", displayName = "лачупес", address = "Lāčupes kapi, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 65L, spokenPhrase = "мэжа", displayName = "мэжа", address = "Meža kapi, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 66L, spokenPhrase = "альфа", displayName = "альфа", address = "Brīvības gatve 372, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 67L, spokenPhrase = "молс", displayName = "молс", address = "Krasta iela 46, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 68L, spokenPhrase = "спица", displayName = "спица", address = "Lielirbes iela 29, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 69L, spokenPhrase = "акрополь", displayName = "акрополь", address = "Maskavas iela 257, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 70L, spokenPhrase = "страдыня", displayName = "страдыня", address = "Pilsoņu iela 13, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 71L, spokenPhrase = "домина", displayName = "домина", address = "Ieriķu iela 3, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 72L, spokenPhrase = "майори", displayName = "майори", address = "Jomas iela, Jūrmala, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 73L, spokenPhrase = "сейм", displayName = "сейм", address = "Jēkaba iela 11, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 74L, spokenPhrase = "гертруда", displayName = "гертруда", address = "Ģertrūdes iela, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 75L, spokenPhrase = "мотормузей", displayName = "мотормузей", address = "Sergeja Eizenšteina iela 6, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 76L, spokenPhrase = "этнографический", displayName = "этнографический", address = "Brīvdabas muzejs, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 77L, spokenPhrase = "башня", displayName = "башня", address = "Smilšu iela 20, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 78L, spokenPhrase = "телебашня", displayName = "телебашня", address = "Zaķusalas televīzijas tornis, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 79L, spokenPhrase = "межапарк", displayName = "межапарк", address = "Mežaparks, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 80L, spokenPhrase = "зоопарк", displayName = "зоопарк", address = "Meža prospekts 1, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 81L, spokenPhrase = "кишка", displayName = "кишка", address = "Ķīpsala, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 82L, spokenPhrase = "ботаника", displayName = "ботаника", address = "Kandavas iela 2, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 83L, spokenPhrase = "агентчик", displayName = "агентчик", address = "Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 84L, spokenPhrase = "базар", displayName = "базар", address = "Centrāltirgus, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 85L, spokenPhrase = "лидо", displayName = "лидо", address = "Krasta iela 76, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 86L, spokenPhrase = "арена рига", displayName = "арена рига", address = "Skanstes iela 21, Rīga, Latvija", latitude = 0.0, longitude = 0.0),
        LandmarkEntry(id = 87L, spokenPhrase = "сконто", displayName = "сконто", address = "Hanzas iela 5, Rīga, Latvija", latitude = 0.0, longitude = 0.0)
    )
}
